/*
 * x86-64 Generate Assembly Symbols
 *
 * This program generates assym.h, which contains offsets and constants
 * used by assembly language code.
 */

#include <sys/param.h>
#include <sys/systm.h>
#include <sys/proc.h>
#include <sys/user.h>
#include <mach/machine.h>
#include <mach/machine/thread_status.h>

#include <stdio.h>
#include <stddef.h>

/* Generate offset definition */
#define DEFINE(name, offset) \
	printf("#define\t%s\t%ld\n", name, (long)(offset))

/* Generate size definition */
#define DEFINE_SIZE(name, type) \
	printf("#define\t%s\t%ld\n", name, (long)sizeof(type))

int
main(void)
{
	printf("/*\n");
	printf(" * Automatically generated by genassym.c\n");
	printf(" * DO NOT EDIT\n");
	printf(" */\n\n");

	printf("#ifndef _ASSYM_H_\n");
	printf("#define _ASSYM_H_\n\n");

	/* Thread state offsets */
	printf("/* x86_64_thread_state_t offsets */\n");
	DEFINE("THREAD_RAX", offsetof(x86_64_thread_state_t, rax));
	DEFINE("THREAD_RBX", offsetof(x86_64_thread_state_t, rbx));
	DEFINE("THREAD_RCX", offsetof(x86_64_thread_state_t, rcx));
	DEFINE("THREAD_RDX", offsetof(x86_64_thread_state_t, rdx));
	DEFINE("THREAD_RDI", offsetof(x86_64_thread_state_t, rdi));
	DEFINE("THREAD_RSI", offsetof(x86_64_thread_state_t, rsi));
	DEFINE("THREAD_RBP", offsetof(x86_64_thread_state_t, rbp));
	DEFINE("THREAD_RSP", offsetof(x86_64_thread_state_t, rsp));
	DEFINE("THREAD_R8", offsetof(x86_64_thread_state_t, r8));
	DEFINE("THREAD_R9", offsetof(x86_64_thread_state_t, r9));
	DEFINE("THREAD_R10", offsetof(x86_64_thread_state_t, r10));
	DEFINE("THREAD_R11", offsetof(x86_64_thread_state_t, r11));
	DEFINE("THREAD_R12", offsetof(x86_64_thread_state_t, r12));
	DEFINE("THREAD_R13", offsetof(x86_64_thread_state_t, r13));
	DEFINE("THREAD_R14", offsetof(x86_64_thread_state_t, r14));
	DEFINE("THREAD_R15", offsetof(x86_64_thread_state_t, r15));
	DEFINE("THREAD_RIP", offsetof(x86_64_thread_state_t, rip));
	DEFINE("THREAD_RFLAGS", offsetof(x86_64_thread_state_t, rflags));
	DEFINE("THREAD_CS", offsetof(x86_64_thread_state_t, cs));
	DEFINE("THREAD_FS", offsetof(x86_64_thread_state_t, fs));
	DEFINE("THREAD_GS", offsetof(x86_64_thread_state_t, gs));
	DEFINE_SIZE("THREAD_STATE_SIZE", x86_64_thread_state_t);
	printf("\n");

	/* VM constants */
	printf("/* VM constants */\n");
	DEFINE("VM_MIN_ADDRESS", VM_MIN_ADDRESS);
	DEFINE("VM_MAX_ADDRESS", VM_MAX_ADDRESS);
	DEFINE("VM_MIN_KERNEL_ADDRESS", VM_MIN_KERNEL_ADDRESS);
	DEFINE("VM_MAX_KERNEL_ADDRESS", VM_MAX_KERNEL_ADDRESS);
	printf("\n");

	/* Page size */
	printf("/* Page size */\n");
	DEFINE("X86_64_PGBYTES", X86_64_PGBYTES);
	DEFINE("X86_64_PGSHIFT", X86_64_PGSHIFT);
	printf("\n");

	/* Stack sizes */
	printf("/* Stack sizes */\n");
	DEFINE("KERNSTACK_SIZE", KERNSTACK_SIZE);
	DEFINE("INTSTACK_SIZE", INTSTACK_SIZE);
	printf("\n");

	/* Segment selectors */
	printf("/* Segment selectors */\n");
	DEFINE("KERN_CODE_SELECTOR", 0x08);
	DEFINE("KERN_DATA_SELECTOR", 0x10);
	DEFINE("USER_CODE_SELECTOR", 0x1B);  /* 0x18 + 3 (RPL) */
	DEFINE("USER_DATA_SELECTOR", 0x23);  /* 0x20 + 3 (RPL) */
	printf("\n");

	/* EFLAGS bits */
	printf("/* EFLAGS bits */\n");
	DEFINE("EFL_CF", 0x00001);  /* Carry */
	DEFINE("EFL_PF", 0x00004);  /* Parity */
	DEFINE("EFL_AF", 0x00010);  /* Auxiliary carry */
	DEFINE("EFL_ZF", 0x00040);  /* Zero */
	DEFINE("EFL_SF", 0x00080);  /* Sign */
	DEFINE("EFL_TF", 0x00100);  /* Trap */
	DEFINE("EFL_IF", 0x00200);  /* Interrupt enable */
	DEFINE("EFL_DF", 0x00400);  /* Direction */
	DEFINE("EFL_OF", 0x00800);  /* Overflow */
	DEFINE("EFL_IOPL", 0x03000);  /* I/O privilege level */
	DEFINE("EFL_NT", 0x04000);  /* Nested task */
	DEFINE("EFL_RF", 0x10000);  /* Resume */
	DEFINE("EFL_VM", 0x20000);  /* Virtual 8086 mode */
	DEFINE("EFL_AC", 0x40000);  /* Alignment check */
	printf("\n");

	/* CR0 bits */
	printf("/* CR0 bits */\n");
	DEFINE("CR0_PE", 0x00000001);  /* Protection enable */
	DEFINE("CR0_MP", 0x00000002);  /* Monitor coprocessor */
	DEFINE("CR0_EM", 0x00000004);  /* Emulation */
	DEFINE("CR0_TS", 0x00000008);  /* Task switched */
	DEFINE("CR0_NE", 0x00000020);  /* Numeric error */
	DEFINE("CR0_WP", 0x00010000);  /* Write protect */
	DEFINE("CR0_AM", 0x00040000);  /* Alignment mask */
	DEFINE("CR0_NW", 0x20000000);  /* Not write-through */
	DEFINE("CR0_CD", 0x40000000);  /* Cache disable */
	DEFINE("CR0_PG", 0x80000000);  /* Paging */
	printf("\n");

	/* CR4 bits */
	printf("/* CR4 bits */\n");
	DEFINE("CR4_VME", 0x00000001);  /* Virtual 8086 extensions */
	DEFINE("CR4_PVI", 0x00000002);  /* Protected mode virtual interrupts */
	DEFINE("CR4_TSD", 0x00000004);  /* Time stamp disable */
	DEFINE("CR4_DE", 0x00000008);  /* Debugging extensions */
	DEFINE("CR4_PSE", 0x00000010);  /* Page size extensions */
	DEFINE("CR4_PAE", 0x00000020);  /* Physical address extension */
	DEFINE("CR4_MCE", 0x00000040);  /* Machine check enable */
	DEFINE("CR4_PGE", 0x00000080);  /* Page global enable */
	DEFINE("CR4_OSFXSR", 0x00000200);  /* OS FXSAVE/FXRSTOR support */
	DEFINE("CR4_OSXMMEXCPT", 0x00000400);  /* OS unmasked exception support */
	printf("\n");

	/* MSR addresses */
	printf("/* MSR addresses */\n");
	DEFINE("MSR_EFER", 0xC0000080);  /* Extended Feature Enable Register */
	DEFINE("MSR_STAR", 0xC0000081);  /* System call selectors */
	DEFINE("MSR_LSTAR", 0xC0000082);  /* System call entry point */
	DEFINE("MSR_CSTAR", 0xC0000083);  /* Compatibility mode syscall entry */
	DEFINE("MSR_SFMASK", 0xC0000084);  /* System call flag mask */
	DEFINE("MSR_FS_BASE", 0xC0000100);  /* FS base address */
	DEFINE("MSR_GS_BASE", 0xC0000101);  /* GS base address */
	DEFINE("MSR_KERNEL_GS_BASE", 0xC0000102);  /* Kernel GS base (swapgs) */
	printf("\n");

	/* Exception/interrupt vectors */
	printf("/* Exception/interrupt vectors */\n");
	DEFINE("T_DIVIDE_ERROR", 0);
	DEFINE("T_DEBUG", 1);
	DEFINE("T_NMI", 2);
	DEFINE("T_BREAKPOINT", 3);
	DEFINE("T_OVERFLOW", 4);
	DEFINE("T_OUT_OF_BOUNDS", 5);
	DEFINE("T_INVALID_OPCODE", 6);
	DEFINE("T_NO_FPU", 7);
	DEFINE("T_DOUBLE_FAULT", 8);
	DEFINE("T_INVALID_TSS", 10);
	DEFINE("T_SEGMENT_NOT_PRESENT", 11);
	DEFINE("T_STACK_FAULT", 12);
	DEFINE("T_GENERAL_PROTECTION", 13);
	DEFINE("T_PAGE_FAULT", 14);
	DEFINE("T_FPU_ERROR", 16);
	DEFINE("T_ALIGNMENT_CHECK", 17);
	DEFINE("T_MACHINE_CHECK", 18);
	DEFINE("T_SIMD_ERROR", 19);
	printf("\n");

	printf("#endif /* _ASSYM_H_ */\n");

	return 0;
}
