/*
 * Copyright (c) 1999 Apple Computer, Inc. All rights reserved.
 *
 * @APPLE_LICENSE_HEADER_START@
 *
 * Portions Copyright (c) 1999 Apple Computer, Inc.  All Rights
 * Reserved.  This file contains Original Code and/or Modifications of
 * Original Code as defined in and that are subject to the Apple Public
 * Source License Version 1.1 (the "License").  You may not use this file
 * except in compliance with the License.  Please obtain a copy of the
 * License at http://www.apple.com/publicsource and read it before using
 * this file.
 *
 * The Original Code and all software distributed under the License are
 * distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE OR NON- INFRINGEMENT.  Please see the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * @APPLE_LICENSE_HEADER_END@
 */

/*
 * IA64 genassym.c - Generate assembly language constants
 *
 * This file is compiled and run to generate assym.s, which contains
 * #define's for structure offsets and other constants needed by
 * assembly language code.
 */

#include <sys/types.h>
#include <sys/param.h>
#include <sys/proc.h>
#include <sys/user.h>
#include <mach/machine/vm_param.h>

/* Output format: #define NAME value */
#define DEFINE(name, value) \
	printf("#define\t%s\t%ld\n", name, (long)(value))

#define OFFSET(structure, member) \
	DEFINE(#structure "_" #member, offsetof(struct structure, member))

int
main(void)
{
	printf("/*\n");
	printf(" * Automatically generated by genassym.c\n");
	printf(" * DO NOT EDIT\n");
	printf(" */\n\n");

	/*
	 * Page size constants
	 */
	DEFINE("IA64_PGBYTES", IA64_PGBYTES);
	DEFINE("IA64_PGSHIFT", IA64_PGSHIFT);
	DEFINE("KERNSTACK_SIZE", KERNSTACK_SIZE);
	DEFINE("INTSTACK_SIZE", INTSTACK_SIZE);

	/*
	 * Register counts
	 */
	DEFINE("IA64_NGREGS", 128);	/* General registers */
	DEFINE("IA64_NFREGS", 128);	/* Floating-point registers */
	DEFINE("IA64_NBREGS", 8);	/* Branch registers */
	DEFINE("IA64_NPREGS", 64);	/* Predicate registers */

	/*
	 * PSR bit positions
	 */
	DEFINE("PSR_BE", 1);	/* Big-endian */
	DEFINE("PSR_IC", 13);	/* Interruption Collection */
	DEFINE("PSR_I", 14);	/* Interrupt enable */
	DEFINE("PSR_DT", 17);	/* Data Translation */
	DEFINE("PSR_IT", 36);	/* Instruction Translation */
	DEFINE("PSR_DB", 24);	/* Debug Breakpoint */
	DEFINE("PSR_SS", 40);	/* Single Step */
	DEFINE("PSR_IS", 34);	/* Instruction Set (IA-64 vs x86) */

	/*
	 * Exception/Interrupt vector offsets
	 */
	DEFINE("EXC_VHPT_TRANS", 0x0000);	/* VHPT Translation */
	DEFINE("EXC_INST_TLB", 0x0400);		/* Instruction TLB */
	DEFINE("EXC_DATA_TLB", 0x0800);		/* Data TLB */
	DEFINE("EXC_ALT_INST_TLB", 0x0c00);	/* Alt Instruction TLB */
	DEFINE("EXC_ALT_DATA_TLB", 0x1000);	/* Alt Data TLB */
	DEFINE("EXC_DATA_NESTED_TLB", 0x1400);	/* Data Nested TLB */
	DEFINE("EXC_INST_KEY_MISS", 0x1800);	/* Instruction Key Miss */
	DEFINE("EXC_DATA_KEY_MISS", 0x1c00);	/* Data Key Miss */
	DEFINE("EXC_DIRTY_BIT", 0x2000);	/* Dirty Bit */
	DEFINE("EXC_INST_ACCESS_BIT", 0x2400);	/* Instruction Access Bit */
	DEFINE("EXC_DATA_ACCESS_BIT", 0x2800);	/* Data Access Bit */
	DEFINE("EXC_BREAK_INST", 0x2c00);	/* Break Instruction */
	DEFINE("EXC_EXTERNAL_INT", 0x3000);	/* External Interrupt */

	/*
	 * Process/thread structure offsets would go here
	 * (when those structures are defined)
	 */

	return 0;
}
